let dataHotels = [
    {
        id: "ho1",
        name: "Ibis Paris Tour Eiffel Cambronne 15ème ",
        photo: ["https://media.staticontent.com/media/pictures/0ee0c769-c98f-4671-912b-32d96d65b9a4/1280x570",
                "https://th.bing.com/th/id/OIP.HQIuz8EnaFRy0mYblLijnwHaFj?pid=ImgDet&rs=1",
                "https://th.bing.com/th/id/OIP.QjaW1rfaaTgRlXn1MARTFwHaD5?pid=ImgDet&rs=1",
        ],
        capacity: "1500",
        citiID: "city1",
        userId: ""
    },{
        id: "ho2",
        name: "Atlantis Dubai Hotel",
        photo: ("https://www.tripsavvy.com/thmb/mzH-Qot3CPBfG7Fyj_gyAnSk2uo=/5323x3460/filters:fill(auto,1)/the-palm-jumeirah-and-atlantis-hotel-in-dubai--614620458-5c89343cc9e77c0001423014.jpg",
                "https://th.bing.com/th/id/R.44ea8e4f7e322a36657e4270c6c85947?rik=K97kFUl7c05eyw&pid=ImgRaw&r=0",
                "https://i.pinimg.com/originals/fc/0e/67/fc0e672a8207e855e3dbeaf87c96f103.jpg"),
        capacity: "10000",
        citiID: "city2",
        userId: ""
    },{
        id: "ho3",
        name: "Mövenpick Hotel Amsterdam City Centre",
        photo: ["https://cf.bstatic.com/images/hotel/max1024x768/275/275218911.jpg",
                "https://th.bing.com/th/id/OIP.lu8tDHmI6gkPNhGgNLMa0AHaEY?pid=ImgDet&rs=1",
                "https://th.bing.com/th/id/OIP.k7nRWje6wQLN53NSnFtTmAHaE8?pid=ImgDet&rs=1",
            ],
        capacity: "2000",
        citiID: "city3",
        userId: ""
    },{
        id: "ho4",
        name: "The Principal Madrid Hotel",
        photo: ["https://photos.hotelbeds.com/giata/bigger/40/407811/407811a_hb_a_002.jpg",
                "https://th.bing.com/th/id/OIP.kIiyzIjCMBpSVIEIVZtL9wHaFj?pid=ImgDet&rs=1",
                "https://media.cntraveler.com/photos/5ceda2158ce15e4031f372df/master/w_1200,c_limit/The-Principal-Madrid-Hotel_201929_Solarium.jpg",
        ],
        capacity: "3500",
        citiID: "city4",
        userId: ""
    },{
        id: "ho5",
        name: "NH Collection Roma Giustiniano",
        photo: ["https://th.bing.com/th/id/OIP.8otCiBlRVB0EGmTDRPMm6AHaEo?pid=ImgDet&rs=1",
                "https://www.viajeselcorteingles.es/imagenes/tm/europa/italia-it/rom-roma/romro-roma/gbwbzmdt/mdm-2018-giustiniano-0639-hdr_x.jpg",
                "https://th.bing.com/th/id/OIP.zyO7SYaGaJxIpnCj5PT44AHaE8?pid=ImgDet&rs=1",
        ],
        capacity: "4000",
        citiID: "city5",
        userId: ""
    },{
        id: "ho6",
        name: "Hotel Riu Plaza Berlin",
        photo: ["https://th.bing.com/th/id/OIP.9Iv1E1EiLIU5siYRvxZn0AHaFG?pid=ImgDet&rs=1",
                "https://th.bing.com/th/id/OIP.iVl5iT5XF6cBvbNhGWBX1QHaE8?pid=ImgDet&rs=1",
                "https://th.bing.com/th/id/R.d14ccb8fe75fc4a0cf5021b47b1bce92?rik=%2fZlagSmwdcGLIA&riu=http%3a%2f%2fhotel-riu-plaza-berlin.hotel-in-berlin.org%2fdata%2fPhotos%2f767x430%2f7796%2f779623%2f779623398.JPEG&ehk=vrDGhb%2f1tys911YPmoIlzM62ymooTxBvDEecC1MKzk8%3d&risl=&pid=ImgRaw&r=0",
        ],
        capacity: "1300",
        citiID: "city6",
        userId: ""
    },{
        id: "ho7",
        name: "Hotel Giraffe by Library Hotel Collection",
        photo: ["https://i.travelapi.com/hotels/1000000/460000/455900/455867/8da85261_z.jpg",
                "https://www.momondo.fr/rimg/himg/4c/ab/b3/arbisoftimages-64825-1361456-130607.jpg?width=2160&height=1215&crop=true",
                "https://res.cloudinary.com/lastminute/image/upload/c_scale,w_630/q_auto/v1541442877/fxaizn9hcxp9828hnckj.jpg",
        ],
        capacity: "4000",
        citiID: "city7",
        userId: ""
    },{
        id: "ho8",
        name: "K+K Hotel George Kensington",
        photo: ["https://th.bing.com/th/id/OIP.QFQtPktTlM9B7fJM4d2T_wAAAA?pid=ImgDet&rs=1",
                "https://www.kkhotels.com/wp-content/uploads/2020/06/StudioGardenAccess.jpg",
                "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/271822004.jpg?k=d4aeb0ed02787064dcac3376d4e3c9ffb7e4e83abcce0050b3f5026b82b0f35b&o=",
        ],
        capacity: "",
        citiID: "city8",
        userId: ""
    },{
        id: "ho9",
        name: "NH Collection München Bavaria",
        photo: ["https://th.bing.com/th/id/R.892213fedecfa3ebbd22e4da4e812b1c?rik=Tj5AAu3X%2b7XDaA&pid=ImgRaw&r=0",
                "https://th.bing.com/th/id/OIP.WMgCxaovmnV7XupuUUSHhQHaE8?pid=ImgDet&rs=1",
                "https://i.animod.de/images/hotel/10951/NH-Collection-Muenchen-Bavaria-8!w750,h550.jpg",
        ],
        capacity: "5000",
        citiID: "city9",
        userId: ""
    },{
        id: "ho10",
        name: "Alma Barcelona",
        photo: ["https://th.bing.com/th/id/R.a502d3d8becb6e43514f9f00b8dad7c5?rik=neWrueaxCwH00w&riu=http%3a%2f%2fwww.myboutiquehotel.com%2fphotos%2f5862%2falma-barcelona-barcelona-028-44334-960x600.jpg&ehk=aUQN6I5lbAkDQHpNBYCfG2YWH4B1rAlHuo%2b15Ef1Jp8%3d&risl=&pid=ImgRaw&r=0",
                "https://a.otcdn.com/imglib/hotelfotos/8/243/hotel-alma-barcelona-051.jpg",
                "https://barcelonanavigator.com/wp-content/uploads/2016/07/Reception.jpg",
        ],
        capacity: "7000",
        citiID: "city10",
        userId: ""
    },{
        id: "ho11",
        name: "Austria Trend Parkhotel Schönbrunn Wien",
        photo: ["https://th.bing.com/th/id/OIP.Te4bJDx5dN4IRNVyN8YqPQHaFj?pid=ImgDet&rs=1",
                "https://kidslovevienna.com/wp-content/uploads/user-uploads/Parkhotel%20Austria%20Trend%20Hotel%20Hietzing%20004.jpg",
                "https://th.bing.com/th/id/OIP.liq4SJzCQDMl14YuIfB-WQHaDW?pid=ImgDet&rs=1",
        ],
        capacity: "3000",
        citiID: "city11",
        userId: ""
    },{
        id: "ho12",
        name: "NH Collection Milano President",
        photo: ["https://www.viajeselcorteingles.es/imagenes/tm/europa/italia-it/mil-milan/milmi-milan/mlfgfd99/mdm-00-16milmi631-f-nh-collection-president-273_x.jpg",
                "https://alenabatsevichute.com/wp-content/uploads/2020/11/nh_collection_milano_president3.jpg",
                "https://th.bing.com/th/id/OIP.kfWdsdVCs5p8gEMLVTU_XwHaD9?pid=ImgDet&rs=1",
        ],
        capacity: "2500",
        citiID: "city12",
        userId: ""
    },{
        id:"it1",
        hoteliD:"ho1",
        name:"AC/DC",
        description:"are an Australian rock band formed in Sydney, New South Wales, Australia in 1973 by Scottish-born brothers Malcolm and Angus Young.Their music has been variously described as hard rock, blues rock, and heavy metal,[2] but the band calls it simply rock and roll.",
        photo:"https://images.ecestaticos.com/1n8yNGPOG60rrgy9pbgRMtNls2A=/135x8:2152x1514/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F906%2Fa1a%2F498%2F906a1a49814f8fad9e920d0622380882.jpg",
        price:"50",
        date:"",
        userId:"",
    },{
        id:"it2",
        hoteliD:"ho1",
        name:"Aerosmith",
        description:"is an American rock band formed in Boston in 1970.The group consists of Steven Tyler (lead vocals), Joe Perry (guitar), Tom Hamilton (bass), Joey Kramer (drums) and Brad Whitford (guitar). Their style, which is rooted in blues-based hard rock.",
        photo:"https://crazyminds.es/wp-content/uploads/AEROSMITH.jpg",
        price:"40",
        date:"",
        userId:"",
    },{
        id:"it3",
        hoteliD:"ho2",
        name:"Coldplay",
        description:"are a British rock band formed in London in 1996. They consist of vocalist and pianist Chris Martin, guitarist Jonny Buckland, bassist Guy Berryman, drummer Will Champion and creative director Phil Harvey. They met at University College London and began playing music together from 1996 to 1998, first calling themselves Pectoralz and then Starfish.",
        photo:"https://media.ambito.com/p/667026ed095714244120eeb239a74af7/adjuntos/239/imagenes/039/509/0039509204/1200x675/smart/coldplayjpg.jpg",
        price:"60",
        date:"",
        userId:"",
    },{
        id:"it4",
        hoteliD:"ho2",
        name:"Red Hot Chili Peppers",
        description:"are an American rock band formed in Los Angeles in 1983, comprising vocalist Anthony Kiedis, bassist Flea, drummer Chad Smith, and guitarist John Frusciante. Their music incorporates elements of alternative rock, funk, punk rock, hard rock, hip hop, and psychedelic rock.",
        photo:"https://fmrockandpop.com/media/k2/items/cache/72d156835da82277239908db4fced97f_L.webp?t=20221025_190759",
        price:"40",
        date:"",
        userId:"",
    },{
        id:"it5",
        hoteliD:"ho3",
        name:"The Strokes",
        description:"are an American rock band from New York City. Formed in 1998, the band is composed of lead singer and songwriter Julian Casablancas, guitarists Nick Valensi and Albert Hammond Jr., bassist Nikolai Fraiture, and drummer Fabrizio Moretti. They were a leading group of the early-2000s indie rock revival.",
        photo:"https://indiehoy.com/wp-content/uploads/2021/06/the-strokes.jpg",
        price:"45",
        date:"",
        userId:"",
    },{
        id:"it6",
        hoteliD:"ho3",
        name:"Arctic Monkeys",
        description:" are an English rock band formed in Sheffield in 2002. The group consists of Alex Turner (lead vocals, guitar, keyboards), Jamie Cook (guitar, keyboards), Nick O'Malley (bass guitar, backing vocals), and Matt Helders (drums, backing vocals). Former band member Andy Nicholson (bass guitar, backing vocals) left the band in 2006 shortly after their debut album was released.",
        photo:"https://media.ambito.com/p/a25e8e80684af02e90466fd0ae70b606/adjuntos/239/imagenes/040/098/0040098680/arctic-monkeysjpg.jpg",
        price:"",
        date:"",
        userId:"",
    },{
        id:"it7",
        hoteliD:"ho4",
        name:"Steven Frayne(Dynamo)",
        description:"better known by his stage name Dynamo, is a British magician born in Bradford, West Yorkshire. His television show Dynamo: Magician Impossible ran from July 2011 to September 2014, and saw him win the Best Entertainment Programme award at the 2012 and 2013 Broadcast Awards. Dynamo has toured the world, and his Seeing Is Believing arena tour was seen by over 750,000 people across the UK, Australia, South Africa and New Zealand.",
        photo:"https://s03.s3c.es/imag/_v0/635x250/f/c/1/dynamo.jpg",
        price:"35",
        date:"",
        userId:"",
    },{
        id:"it8",
        hoteliD:"ho4",
        name:"David Blaine",
        description:" is an American illusionist, endurance artist, and extreme performer. He is best known for his high-profile feats of endurance and has set and broken several world records.",
        photo:"https://media.lasvegasmagazine.com/media/img/photos/2022/09/15/David_Blaine_Art_Streiber_LD_t1024.jpg?b3f067808e872500b33dd7ef4ee517933144b05a",
        price:"55",
        date:"",
        userId:"",
    },{
        id:"it9",
        hoteliD:"ho5",
        name:"David Copperfield",
        description:"is an American magic man, described by Forbes as the most commercially successful magician in history.is television specials have been nominated for 38 Emmy Awards, winning 21. Best known for his combination of storytelling and illusion, his career of over 40 years has earned him 11 Guinness World Records",
        photo:"https://mediaim.expedia.com/localexpert/183797/33e309ea-e818-470e-8add-3df549aa942b.jpg?impolicy=resizecrop&rw=1005&rh=565",
        price:"70",
        date:"",
        userId:"",
    },{
        id:"it10",
        hoteliD:"ho5",
        name:"Criss Angel",
        description:" is an American magician, illusionist and musician. Angel began his career in New York City, before moving his base of operations to the Las Vegas Valley. He is known for starring in the television and stage show Criss Angel Mindfreak and his previous live performance illusion show Criss Angel Believe",
        photo:"https://assets.simpleviewcms.com/simpleview/image/fetch/c_limit,h_1200,q_75,w_1200/https://assets.simpleviewinc.com/simpleview/image/upload/crm/lasvegas/criss-angel-show-planet-hollywood_054B445D-F3CE-8C43-E44C71CB60D829BB_054bbcf5-e52b-2fa8-28cec96bf0f43e66.jpg",
        price:"65",
        date:"",
        userId:"",
    },{
        id:"it111",
        hoteliD:"ho6",
        name:"Duki",
        description:"is an Argentine rapper and singer. He is the lead voice of trap music in Argentina, thanks to his multiple hits with his singles and his particular style of voice and staging.",
        photo:"https://cloudfront-us-east-1.images.arcpublishing.com/infobae/JYCHSDTQARGOHDDLD2YOSEX5GQ.JPG",
        price:"43",
        date:"",
        userId:"",
    },{
        id:"it11",
        hoteliD:"ho6",
        name:"Paulo Londra",
        description:"is an Argentine rapper and singer. His music has topped Argentine charts and been highly successful across Argentina and Latin America.",
        photo:"http://www.lauriaweb.com/wp-content/uploads/2018/05/Captura-de-pantalla-2018-05-03-a-las-13.50.54.png",
        price:"40",
        date:"",
        userId:"",
    },
]

export default data